# Generated by Django 2.2.8 on 2022-02-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='guest_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
